version: '3.9'

services:
  java-app:
    build: .
    expose:
      - "8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vacations_requests
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - postgres
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr

  postgres:
    image: postgres:16.2
    container_name: postgres
    environment:
      POSTGRES_DB: vacations_requests
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "8089:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - java-app

volumes:
  postgres_data:
