server:
  port: 8788
spring:
  application:
    name: leaveRequestSystem
  datasource:
    url: jdbc:postgresql://localhost:8081/vacations
    username: <YOUR_NAME>
    password: <YOUR_PASSWORD>
    driver-class-name: org.postgresql.Driver
    initialization-mode: embedded
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
  profiles:
    include: local
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <YOUR_CLIENT_ID>
            client-secret: <YOUR_CLIENT_SECRET>
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
#    root: DEBUG
#spring.jpa.defer-datasource-initialization=true


