server:
  port: 8089
spring:
  application:
    name: leaveRequestSystem
  datasource:
    username: <YOUR_USERNAME>
    password: <YOUR_PASSWORD>
    url: jdbc:postgresql://postgres:5432/vacations_requests
#    url: jdbc:postgresql://localhost:5432/vacations_requests
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
  profiles:
    include: local
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <YOUR_CLIENT_ID>
            client-secret: <YOUR_CLIENT_SECRET>
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
    pl:
      iodkovskaya:
        leaveRequestSystem:
          service: INFO
#  file:
#    name: logs/vacation_balance.log
vacation:
  increment:
    cron: "0 0 0 * * *"
#    root: DEBUG
#spring.jpa.defer-datasource-initialization=true
org:
  jobrunr:
    background-job-server:
      enabled: true
      poll-interval-in-seconds: 5
    dashboard:
      enabled: true
      port: 8000
    jobs:
      default-number-of-retries: 3
      retry-interval: PT10S


