server:
  port: 8787
spring:
  application:
    name: leaveRequestSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/vacations
    username: yourName
    password: yourPassword
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect